
/* v23.0 Aviation + Private Island Assets
   Visible in Assets: vliegbrevet, vliegtuigen kopen/beheren, privé-eiland kopen/beheren.
*/
(function(){
  function clamp230(v,min=0,max=100){return Math.max(min,Math.min(max,Math.round(v||0)))}
  function r230(a,b){return Math.floor(Math.random()*(b-a+1))+a}
  function money230(v){try{return money(v)}catch(e){return '€ '+Math.round(v||0).toLocaleString('nl-NL')}}
  function toast230(t){try{toast(t)}catch(e){console.log(t)}}
  function apply230(s){try{applyStats(s||{})}catch(e){}}
  function saveRender230(){try{safeSave()}catch(e){}try{render()}catch(e){}}
  function rr230(icon,title,sub,fn,locked=false,cls=''){
    try{return row(icon,title,sub,fn,locked,cls)}catch(e){return `<div class="row ${locked?'locked':''} ${cls||''}" onclick="${locked?'':fn}"><div class="rIco">${icon}</div><div><div class="rTitle">${title}</div><div class="sub">${sub||''}</div></div><div class="chev">›</div></div>`}
  }
  function sec230(t){return `<div class="section">${t}</div>`}
  function card230(h){return `<div class="card">${h}</div>`}
  function modal230(icon,title,body,back='closeModal()'){
    showModal(`<div class="modalTop"><div class="avatar">${icon}</div><div class="modalTitle">${title}</div></div><div class="modalBody v230Body">${body}<button class="btn alt" onclick="${back}">Terug</button></div>`);
    setTimeout(clickFix230,0);
  }
  function result230(icon,title,txt,stats={},cash=0,type='good',back='closeModal()'){
    if(cash)state.money=(state.money||0)+cash;
    apply230(stats);
    try{addLog(`<b>${title}</b><br>${txt}`,type,false)}catch(e){}
    saveRender230();
    modal230(icon,title,card230(txt),back);
  }
  function clickFix230(){try{document.querySelectorAll('#modal .row,#modal .btn').forEach(el=>{el.style.pointerEvents='auto';el.style.touchAction='manipulation';el.style.position='relative';el.style.zIndex='9';})}catch(e){}}

  const AIRCRAFT230=[
    {id:'cessna172',icon:'🛩️',name:'Cessna 172 Skyhawk',price:120000,upkeep:12000,reqHours:40,crew:false,desc:'Kleine propellerkist. Perfect na je PPL.'},
    {id:'piperpa28',icon:'🛩️',name:'Piper PA-28 Cherokee',price:180000,upkeep:15000,reqHours:45,crew:false,desc:'Betaalbaar privévliegen met iets meer comfort.'},
    {id:'cirrussr22',icon:'✈️',name:'Cirrus SR22',price:850000,upkeep:38000,reqHours:75,crew:false,desc:'Snelle luxe single-engine privévlieger.'},
    {id:'kingair350',icon:'✈️',name:'Beechcraft King Air 350',price:3500000,upkeep:180000,reqHours:150,crew:true,desc:'Twin turboprop, zakelijk en duur.'},
    {id:'pilatuspc12',icon:'✈️',name:'Pilatus PC-12',price:5000000,upkeep:220000,reqHours:150,crew:true,desc:'Luxe turboprop voor lange afstanden.'},
    {id:'citationm2',icon:'🛫',name:'Cessna Citation M2',price:6500000,upkeep:350000,reqHours:250,crew:true,desc:'Instap private jet met crew/managementkosten.'},
    {id:'phenom300',icon:'🛫',name:'Embraer Phenom 300',price:10000000,upkeep:650000,reqHours:300,crew:true,desc:'Snelle zakenjet met hoge kosten.'},
    {id:'gulfstream',icon:'🛬',name:'Gulfstream G650',price:65000000,upkeep:3200000,reqHours:500,crew:true,desc:'Ultra-luxe long range jet.'}
  ];
  const ISLAND_COST230=100000000;
  const ISLAND_BUILD230={
    house:{icon:'🏡',name:'Eiland villa',cost:2500000,upkeep:90000,comfort:18,tourism:0,stability:1,desc:'Eigen villa op je eiland.'},
    mansion:{icon:'🏰',name:'Mega mansion',cost:18000000,upkeep:450000,comfort:32,tourism:4,stability:1,desc:'Absurd luxe hoofdhuis.'},
    dock:{icon:'⚓',name:'Haven / pier',cost:3500000,upkeep:160000,tourism:12,infra:15,stability:3,desc:'Voor bevoorrading en bezoekers.'},
    airstrip:{icon:'🛬',name:'Privé landingsbaan',cost:12000000,upkeep:500000,tourism:20,infra:22,stability:4,desc:'Maak je eiland bereikbaar met vliegtuig.'},
    solar:{icon:'🔋',name:'Solar + powergrid',cost:7000000,upkeep:220000,infra:20,stability:6,desc:'Stroomvoorziening.'},
    water:{icon:'💧',name:'Waterzuivering',cost:5500000,upkeep:180000,infra:18,stability:7,desc:'Schoon water.'},
    shop:{icon:'🛍️',name:'Winkels / marina shops',cost:4000000,upkeep:240000,tourism:18,income:600000,stability:1,desc:'Winkels voor bezoekers.'},
    resort:{icon:'🏨',name:'Boutique resort',cost:25000000,upkeep:1500000,tourism:35,income:3500000,stability:-2,desc:'Grote inkomsten, meer drukte.'},
    clinic:{icon:'🏥',name:'Kliniek',cost:9000000,upkeep:650000,infra:10,stability:10,desc:'Gezondheid en veiligheid.'},
    security:{icon:'🛡️',name:'Security / kustwacht',cost:6000000,upkeep:480000,stability:14,infra:4,desc:'Minder criminaliteit.'},
    school:{icon:'🏫',name:'School/community center',cost:8000000,upkeep:550000,stability:12,infra:6,desc:'Maakt wonen realistischer.'}
  };
  function ensure230(){
    state.aviation230=state.aviation230||{};
    let a=state.aviation230;
    a.theory=clamp230(a.theory||0); a.flightHours=Number(a.flightHours||0); a.license=!!a.license; a.medical=a.medical!==false; a.aircraft=a.aircraft||[];
    a.aircraft.forEach(p=>{p.condition=clamp230(p.condition??85,1,100);p.hours=Number(p.hours||0);p.rented=!!p.rented;p.upkeep=Number(p.upkeep||0);p.value=Math.max(0,Math.round(p.value||p.price||0));});
    if(state.privateIsland230){let i=state.privateIsland230;i.name=i.name||'Privé-eiland';i.value=Math.max(ISLAND_COST230,Math.round(i.value||ISLAND_COST230));i.buildings=i.buildings||{};i.infrastructure=clamp230(i.infrastructure||10);i.tourism=clamp230(i.tourism||0);i.stability=clamp230(i.stability||50);i.population=Math.max(0,Math.round(i.population||0));i.immigration=i.immigration||'strict';i.laws=i.laws||{tax:'normal',alcohol:'legal',environment:'protected',security:'normal'};i.yearlyIncome=Number(i.yearlyIncome||0);i.yearlyCosts=Number(i.yearlyCosts||0);}
  }
  window.ensureAviationIsland230=ensure230;
  function aviationStatus230(){ensure230();let a=state.aviation230;return card230(`<b>Luchtvaart</b><br>Vliegbrevet: ${a.license?'✅ gehaald':'❌ nog niet'}<br>Theorie: ${a.theory}%<br>Vlieguren: ${a.flightHours.toFixed(1)} uur<br>Vliegtuigen: ${a.aircraft.length}<br><span class="mini">Brevet: theorie 80% + 40 vlieguren + praktijkexamen.</span>`)}
  window.aviationHub230=function(){ensure230();let h=aviationStatus230();h+=sec230('Vliegbrevet');h+=rr230('📚','Theorie studeren','Verhoog theoriekennis','flightTheory230()');h+=rr230('🛩️','Vliegles nemen',`${money230(280)} per les · +1 tot 2 vlieguren`,'flightLesson230()',state.money<280);h+=rr230('🧑‍✈️','Praktijkexamen vliegbrevet',`${money230(1200)} · vereist 80% theorie en 40 uur`,'flightExam230()',state.money<1200||state.aviation230.theory<80||state.aviation230.flightHours<40);h+=sec230('Vliegtuigen');h+=rr230('🛒','Vliegtuig kopen',state.aviation230.license?'Koop privévliegtuigen zoals auto-assets':'Eerst vliegbrevet halen','aircraftMarket230()',!state.aviation230.license);h+=rr230('✈️','Mijn vliegtuigen',state.aviation230.aircraft.length?'Beheer, vliegen, onderhoud, verkopen':'Nog geen vliegtuigen','myAircraft230()',!state.aviation230.aircraft.length);modal230('🛫','Luchtvaart',h,'closeModal()')};
  window.flightTheory230=function(){ensure230();state.aviation230.theory=clamp230(state.aviation230.theory+r230(8,16));result230('📚','Vliegtheorie',`Ik studeerde vliegtheorie. Theorie staat nu op ${state.aviation230.theory}%.`,{Smarts:2,Stamina:-3},0,'good','aviationHub230()')};
  window.flightLesson230=function(){ensure230();if(state.money<280)return toast230('Niet genoeg geld voor vliegles.');state.money-=280;let hrs=Math.round((1+Math.random()*1.2)*10)/10;state.aviation230.flightHours+=hrs;state.aviation230.theory=clamp230(state.aviation230.theory+r230(1,4));result230('🛩️','Vliegles',`Ik nam vliegles. +${hrs} vlieguren.<br>Totaal: ${state.aviation230.flightHours.toFixed(1)} uur.`,{Smarts:1,Happiness:3,Stamina:-6},0,'good','aviationHub230()')};
  window.flightExam230=function(){ensure230();let a=state.aviation230;if(a.theory<80||a.flightHours<40)return toast230('Je hebt 80% theorie en 40 vlieguren nodig.');if(state.money<1200)return toast230('Niet genoeg geld voor examen.');state.money-=1200;let chance=.55+(a.theory-80)/80+(a.flightHours-40)/160+(state.stats?.Smarts||50)/500;if(Math.random()<chance){a.license=true;result230('🧑‍✈️','Vliegbrevet gehaald','Ik slaagde voor mijn praktijkexamen. Ik heb nu mijn vliegbrevet en kan vliegtuigen kopen.',{Happiness:12,Smarts:3},0,'good','aviationHub230()')}else result230('🧑‍✈️','Examen gezakt','Ik zakte voor mijn praktijkexamen. Meer vlieguren en theorie helpen.',{Happiness:-6,Smarts:1},0,'warn','aviationHub230()')};
  window.aircraftMarket230=function(){ensure230();if(!state.aviation230.license)return toast230('Eerst vliegbrevet halen.');let h=aviationStatus230()+sec230('Vliegtuigen kopen');AIRCRAFT230.forEach((p,idx)=>{let locked=state.money<p.price||state.aviation230.flightHours<p.reqHours;h+=rr230(p.icon,p.name,`${money230(p.price)} · onderhoud ${money230(p.upkeep)}/jr · vereist ${p.reqHours} vlieguren · ${p.desc}`,`buyAircraft230(${idx})`,locked)});modal230('🛒','Vliegtuig kopen',h,'aviationHub230()')};
  window.buyAircraft230=function(idx){ensure230();let p=AIRCRAFT230[idx];if(!p)return;if(!state.aviation230.license)return toast230('Eerst vliegbrevet halen.');if(state.aviation230.flightHours<p.reqHours)return toast230('Te weinig vlieguren.');if(state.money<p.price)return toast230('Niet genoeg geld.');state.money-=p.price;state.aviation230.aircraft.push({id:p.id,icon:p.icon,name:p.name,price:p.price,value:Math.round(p.price*.88),upkeep:p.upkeep,condition:86,hours:0,crew:p.crew,boughtAge:state.age,rented:false});result230(p.icon,'Vliegtuig gekocht',`Ik kocht een ${p.name} voor ${money230(p.price)}.`,{Happiness:8,Smarts:2},0,'good','aviationHub230()')};
  window.myAircraft230=function(){ensure230();let h=aviationStatus230()+sec230('Mijn vliegtuigen');h+=state.aviation230.aircraft.map((a,i)=>rr230(a.icon||'✈️',a.name,`${money230(a.value)} · staat ${a.condition}% · ${a.hours.toFixed(1)} uur · ${a.rented?'verhuurd':'eigen gebruik'}`,`aircraftDetail230(${i})`)).join('')||card230('Nog geen vliegtuigen.');modal230('✈️','Mijn vliegtuigen',h,'aviationHub230()')};
  window.aircraftDetail230=function(i){ensure230();let a=state.aviation230.aircraft[i];if(!a)return myAircraft230();let h=card230(`<b>${a.name}</b><br>Waarde: ${money230(a.value)}<br>Staat: ${a.condition}%<br>Uren: ${a.hours.toFixed(1)}<br>Onderhoud: ${money230(a.upkeep)}/jr<br>${a.crew?'Crew/management nodig.<br>':''}${a.rented?'Status: charter/verhuur':'Status: eigen gebruik'}`);h+=sec230('Beheer');h+=rr230('🛫','Privévlucht maken','Happiness omhoog, uren erbij, conditie omlaag','flyAircraft230('+i+')',a.condition<35);h+=rr230('🛠️','Onderhoud uitvoeren',`${money230(Math.round(a.upkeep*.35))} · conditie omhoog`,'maintainAircraft230('+i+')',state.money<Math.round(a.upkeep*.35));h+=rr230('💼',a.rented?'Stop charter/verhuur':'Charter/verhuur aanzetten',a.rented?'Geen jaarlijkse charterinkomsten meer':'Jaarlijkse inkomsten, extra slijtage','toggleAircraftRent230('+i+')');h+=rr230('💰','Verkopen',`Verkoop voor ongeveer ${money230(a.value)}`,'sellAircraft230('+i+')');modal230(a.icon||'✈️',a.name,h,'myAircraft230()')};
  window.flyAircraft230=function(i){ensure230();let a=state.aviation230.aircraft[i];if(!a)return;if(a.condition<35)return toast230('Te slechte staat. Eerst onderhoud.');let hrs=Math.round((1+r230(1,5))*10)/10;a.hours+=hrs;state.aviation230.flightHours+=hrs;a.condition=clamp230(a.condition-r230(2,7),1,100);result230('🛫','Privévlucht',`Ik maakte een privévlucht met mijn ${a.name}. +${hrs} vlieguren.`,{Happiness:8,Stamina:-6,Smarts:1},0,'good','aircraftDetail230('+i+')')};
  window.maintainAircraft230=function(i){ensure230();let a=state.aviation230.aircraft[i];if(!a)return;let cost=Math.round(a.upkeep*.35);if(state.money<cost)return toast230('Niet genoeg geld voor onderhoud.');state.money-=cost;a.condition=clamp230(a.condition+r230(20,36),1,100);a.value=Math.round(a.value*1.03);result230('🛠️','Vliegtuig onderhoud',`Onderhoud uitgevoerd voor ${money230(cost)}. Staat nu ${a.condition}%.`,{Smarts:1},0,'good','aircraftDetail230('+i+')')};
  window.toggleAircraftRent230=function(i){ensure230();let a=state.aviation230.aircraft[i];if(!a)return;a.rented=!a.rented;result230('💼','Aircraft charter',a.rented?`Ik zette mijn ${a.name} beschikbaar voor charter/verhuur.`:`Ik stopte charter/verhuur voor mijn ${a.name}.`,{Smarts:1},0,a.rented?'good':'warn','aircraftDetail230('+i+')')};
  window.sellAircraft230=function(i){ensure230();let a=state.aviation230.aircraft[i];if(!a)return;state.money+=a.value;state.aviation230.aircraft.splice(i,1);result230('💰','Vliegtuig verkocht',`Ik verkocht mijn ${a.name} voor ${money230(a.value)}.`,{Happiness:1},0,'good','myAircraft230()')};
  function island230(){ensure230();return state.privateIsland230}
  function islandCard230(){let i=island230();if(!i)return card230(`<b>Privé-eiland</b><br>Nog niet gekocht.<br>Prijs: ${money230(ISLAND_COST230)}.`);return card230(`<b>${i.name}</b><br>Waarde: ${money230(i.value)}<br>Populatie: ${i.population}<br>Infrastructuur: ${i.infrastructure}%<br>Toerisme: ${i.tourism}%<br>Stabiliteit: ${i.stability}%<br>Immigratie: ${i.immigration}<br>Jaarinkomsten: ${money230(i.yearlyIncome||0)} · kosten: ${money230(i.yearlyCosts||0)}`)}
  window.privateIslandHub230=function(){ensure230();let h=islandCard230();if(!state.privateIsland230){h+=rr230('🏝️','Privé-eiland kopen',`${money230(ISLAND_COST230)} · daarna kun je wetten/infrastructuur/winkels beheren`,'buyPrivateIsland230()',state.money<ISLAND_COST230);modal230('🏝️','Privé-eiland',h,'closeModal()');return;}h+=sec230('Bouwen');Object.entries(ISLAND_BUILD230).forEach(([k,b])=>{let already=!!state.privateIsland230.buildings[k];h+=rr230(b.icon,b.name,already?'Gebouwd':`${money230(b.cost)} · ${b.desc}`,`buildIsland230('${k}')`,already||state.money<b.cost)});h+=sec230('Beleid');h+=rr230('🛂','Immigratiebeleid','Bepaal wie op het eiland mag wonen/werken','islandImmigration230()');h+=rr230('⚖️','Lokale wetten','Belasting, alcohol, milieu en security','islandLaws230()');h+=rr230('📊','Eiland jaarupdate handmatig','Simuleer inkomsten/kosten/stabiliteit','processIslandYear230(true)');modal230('🏝️','Privé-eiland beheren',h,'closeModal()')};
  window.buyPrivateIsland230=function(){ensure230();if(state.privateIsland230)return privateIslandHub230();if(state.money<ISLAND_COST230)return toast230('Niet genoeg geld. Eiland kost '+money230(ISLAND_COST230));state.money-=ISLAND_COST230;state.privateIsland230={name:'Privé-eiland',value:ISLAND_COST230,boughtAge:state.age,buildings:{},infrastructure:10,tourism:0,stability:55,population:0,immigration:'strict',laws:{tax:'normal',alcohol:'legal',environment:'protected',security:'normal'},yearlyIncome:0,yearlyCosts:750000};result230('🏝️','Privé-eiland gekocht',`Ik kocht een privé-eiland voor ${money230(ISLAND_COST230)}. Nu kan ik er huizen, winkels, infrastructuur en regels op bouwen.`,{Happiness:25,Smarts:5},0,'good','privateIslandHub230()')};
  window.buildIsland230=function(key){ensure230();let i=state.privateIsland230,b=ISLAND_BUILD230[key];if(!i||!b)return;if(i.buildings[key])return toast230('Dit is al gebouwd.');if(state.money<b.cost)return toast230('Niet genoeg geld.');state.money-=b.cost;i.buildings[key]={builtAge:state.age,cost:b.cost};i.value+=Math.round(b.cost*.80);i.infrastructure=clamp230(i.infrastructure+(b.infra||0));i.tourism=clamp230(i.tourism+(b.tourism||0));i.stability=clamp230(i.stability+(b.stability||0));i.yearlyCosts+=b.upkeep||0;i.yearlyIncome+=b.income||0;if(key==='house'||key==='mansion'){state.houses=state.houses||[];state.houses.push({name:b.name+' op privé-eiland',owned:true,primary:false,value:b.cost,upkeep:b.upkeep||0,icon:b.icon,world:'privateIsland',condition:90,quality:90,comfort:90,security:80,energy:70,rooms:key==='mansion'?9:5});}result230(b.icon,'Eiland bouwproject',`${b.name} gebouwd voor ${money230(b.cost)}.`,{Happiness:5,Smarts:2},0,'good','privateIslandHub230()')};
  window.islandImmigration230=function(){let opts=[['closed','Gesloten','Bijna niemand mag wonen/werken.'],['strict','Streng','Alleen rijke/betrouwbare bewoners en personeel.'],['skilled','Skilled workers','Werkers voor resort, shops en infrastructuur.'],['open','Open immigratie','Snelle groei, meer inkomsten maar meer risico.']];let h=islandCard230()+sec230('Immigratiebeleid');opts.forEach(o=>h+=rr230('🛂',o[1],o[2],`setIslandImmigration230('${o[0]}')`));modal230('🛂','Immigratiebeleid',h,'privateIslandHub230()')};
  window.setIslandImmigration230=function(policy){ensure230();if(!state.privateIsland230)return;state.privateIsland230.immigration=policy;result230('🛂','Immigratiebeleid',`Nieuw immigratiebeleid: ${policy}.`,{Smarts:2},0,'good','privateIslandHub230()')};
  window.islandLaws230=function(){let i=island230();if(!i)return;let h=islandCard230()+sec230('Belasting');h+=rr230('💸','Lage belasting','Meer rijke bewoners/toerisme, minder directe inkomsten','setIslandLaw230("tax","low")');h+=rr230('⚖️','Normale belasting','Balans tussen inkomsten en stabiliteit','setIslandLaw230("tax","normal")');h+=rr230('🏦','Hoge belasting','Meer inkomsten, minder groei/stabiliteit','setIslandLaw230("tax","high")');h+=sec230('Regels');h+=rr230('🍹','Alcohol vrij','Meer nightlife/toerisme, iets meer risico','setIslandLaw230("alcohol","legal")');h+=rr230('🚫','Alcohol beperkt','Rustiger eiland, minder nightlife inkomsten','setIslandLaw230("alcohol","limited")');h+=rr230('🌿','Milieu beschermd','Stabiliteit/waarde omhoog','setIslandLaw230("environment","protected")');h+=rr230('🏗️','Business first','Meer groei/inkomsten, stabiliteit omlaag','setIslandLaw230("environment","business")');h+=rr230('🛡️','Strenge security','Stabiliteit omhoog, jaarlijkse kosten hoger','setIslandLaw230("security","strict")');h+=rr230('🙂','Normale security','Goedkoper, iets meer risico','setIslandLaw230("security","normal")');modal230('⚖️','Lokale wetten',h,'privateIslandHub230()')};
  window.setIslandLaw230=function(k,v){ensure230();if(!state.privateIsland230)return;state.privateIsland230.laws=state.privateIsland230.laws||{};state.privateIsland230.laws[k]=v;result230('⚖️','Lokale wet aangepast',`${k} staat nu op: ${v}.`,{Smarts:2},0,'good','islandLaws230()')};
  window.processAviationYear230=function(){ensure230();let lines=[];state.aviation230.aircraft.forEach(a=>{let cost=a.upkeep||0,income=0;if(a.rented){income=Math.round((a.value||a.price||0)*0.07);a.condition=clamp230(a.condition-r230(8,18));}else a.condition=clamp230(a.condition-r230(3,9));state.money+=income-cost;a.value=Math.max(0,Math.round(a.value*(0.94+(a.condition/100)*0.04)));lines.push(`${a.icon} ${a.name}: ${income?`charter ${money230(income)} · `:''}kosten ${money230(cost)} · staat ${a.condition}%`)});if(lines.length)try{addLog('<b>Vliegtuigen jaarupdate</b><br>'+lines.join('<br>'),'warn',false)}catch(e){}};
  window.processIslandYear230=function(manual=false){ensure230();let i=state.privateIsland230;if(!i)return;let growth=0,income=i.yearlyIncome||0,costs=i.yearlyCosts||750000;if(i.immigration==='closed'){growth=0;i.stability=clamp230(i.stability+r230(1,4));}if(i.immigration==='strict'){growth=r230(0,2);i.stability=clamp230(i.stability+r230(0,3));}if(i.immigration==='skilled'){growth=r230(2,8);income+=r230(50000,250000);i.stability=clamp230(i.stability+r230(-1,2));}if(i.immigration==='open'){growth=r230(8,28);income+=r230(100000,650000);i.stability=clamp230(i.stability-r230(1,6));}if(i.laws?.tax==='low'){income=Math.round(income*.85);i.tourism=clamp230(i.tourism+2)}if(i.laws?.tax==='high'){income=Math.round(income*1.25);i.stability=clamp230(i.stability-2)}if(i.laws?.environment==='protected'){i.value=Math.round(i.value*1.015);i.stability=clamp230(i.stability+2)}if(i.laws?.environment==='business'){income=Math.round(income*1.15);i.stability=clamp230(i.stability-2)}if(i.laws?.security==='strict'){costs+=500000;i.stability=clamp230(i.stability+4)}if(i.laws?.alcohol==='legal'){income+=Math.round((i.tourism||0)*8000);i.stability=clamp230(i.stability-1)}i.population+=growth;let net=income-costs;state.money+=net;i.value=Math.round(i.value+(net>0?net*.35:net*.1)+i.infrastructure*25000+i.tourism*20000+i.stability*15000);try{addLog(`<b>Privé-eiland jaarupdate</b><br>Inkomsten: ${money230(income)}<br>Kosten: ${money230(costs)}<br>Netto: ${money230(net)}<br>Populatie +${growth}<br>Waarde: ${money230(i.value)}<br>Stabiliteit: ${i.stability}%`,'warn',false)}catch(e){}if(manual){saveRender230();privateIslandHub230();}};
  const oldAssets230=window.assetsHTML||(typeof assetsHTML==='function'?assetsHTML:null);if(oldAssets230&&!oldAssets230.__aviationIsland230){window.assetsHTML=function(){ensure230();let html=oldAssets230.apply(this,arguments);let a=state.aviation230,island=state.privateIsland230,block='';block+=sec230('Luchtvaart & Privé-eiland');block+=rr230('🧑‍✈️','Vliegbrevet & vliegtuigen',a.license?`${a.aircraft.length} vliegtuigen · ${a.flightHours.toFixed(1)} vlieguren`:`Brevet halen: theorie ${a.theory}% · ${a.flightHours.toFixed(1)} vlieguren`,'aviationHub230()',state.age<18);block+=rr230('🛒','Vliegtuig kopen',a.license?'Koop vliegtuigen met realistische prijzen':'Eerst vliegbrevet halen','aircraftMarket230()',state.age<18||!a.license);block+=rr230('🏝️','Privé-eiland',island?`Waarde ${money230(island.value)} · infra ${island.infrastructure}% · stabiliteit ${island.stability}%`:`Kopen voor ${money230(ISLAND_COST230)}`,'privateIslandHub230()',state.age<18||(state.money<ISLAND_COST230&&!island));if(a.aircraft.length){block+=sec230('Mijn vliegtuigen');block+=a.aircraft.map((p,i)=>rr230(p.icon||'✈️',p.name,`${money230(p.value)} · staat ${p.condition}% · ${p.rented?'charter':'eigen gebruik'}`,`aircraftDetail230(${i})`)).join('')}if(island){block+=sec230('Mijn privé-eiland');block+=rr230('🏝️',island.name,`Waarde ${money230(island.value)} · bevolking ${island.population} · inkomsten ${money230(island.yearlyIncome)}/jr`,'privateIslandHub230()')}if(!String(html).includes('Luchtvaart & Privé-eiland'))html+=block;return html};window.assetsHTML.__aviationIsland230=true;try{assetsHTML=window.assetsHTML}catch(e){}}
  const oldYear230=window.yearlyAssets||(typeof yearlyAssets==='function'?yearlyAssets:null);if(oldYear230&&!oldYear230.__aviationIsland230){window.yearlyAssets=function(){if(oldYear230)oldYear230.apply(this,arguments);try{processAviationYear230();processIslandYear230(false)}catch(e){console.warn('[v23.0 aviation/island]',e)}};window.yearlyAssets.__aviationIsland230=true;try{yearlyAssets=window.yearlyAssets}catch(e){}}
  const oldAge230=window.ageUp||(typeof ageUp==='function'?ageUp:null);if(oldAge230&&!oldAge230.__aviationIsland230){window.ageUp=function(){let before=state&&state.age;let ret=oldAge230.apply(this,arguments);try{if(state&&state.age!==before){processAviationYear230();processIslandYear230(false)}safeSave();render()}catch(e){}return ret};window.ageUp.__aviationIsland230=true;try{ageUp=window.ageUp}catch(e){}}
  const oldSave230=window.safeSave||(typeof safeSave==='function'?safeSave:null);if(oldSave230&&!oldSave230.__aviationIsland230){window.safeSave=function(){try{ensure230()}catch(e){}return oldSave230.apply(this,arguments)};window.safeSave.__aviationIsland230=true;try{safeSave=window.safeSave}catch(e){}}
  window.debugAviationIsland230=function(){ensure230();let h=aviationStatus230()+islandCard230();h+=rr230('🧑‍✈️','Open luchtvaart','Brevet/vliegtuig kopen','aviationHub230()');h+=rr230('🏝️','Open privé-eiland','Eiland kopen/beheren','privateIslandHub230()');modal230('🛠️','Aviation/Island debug',h,'closeModal()')};
  setTimeout(()=>{try{ensure230();safeSave();render()}catch(e){}},300);
})();
